/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked_list;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Before;
import org.w3c.dom.Node;

import java.util.ArrayList;
import java.util.List;

public class LibraryTest {
    private Library testList;
    @Before
    public void init() {
        testList = new Library();
    }


    @Test
    public void emptyInitiatedList() {
        assertNull("Empty linked list head should be null", testList.head);
    }

    @Test
    public void insertOneIntoNewList() {
        testList.insert(1);
        assertTrue("Value of 1 is in list", testList.includes(1));
        assertFalse("2 is not in list", testList.includes(2));
    }

    @Test
    public void insertThreeValue() {
        testList.insert(1);
        testList.insert(2);
        testList.insert(3);
        List<Integer> result = new ArrayList<>();
        result.add(1);
        result.add(2);
        result.add(3);

        assertEquals("ArrayList should return three", "[1, 2, 3]", result.toString());
    }

    @Test
    public void returnEmptyList() {
        assertEquals("Empty list", "[]", testList.print().toString());
    }

    @Test
    public void testInsertBeforeFirstNode(){
        emptyInitiatedList();
        List<Integer> result = new ArrayList<>();
        result.add(1);
        result.add(3);
        testList.insertBefore(3, 2);
        System.out.println(result);

    }

    @Test
    public void testKthValue(){
        testList.append(1);
        testList.append(3);
        testList.append(5);
        testList.append(20);
        testList.append(11);

        assertEquals("Should return the kth value.", 5, testList.getKthValue(2));
    }

    @Test
    public void testPushAndPop() {
        testList.push(50);
        testList.push(70);
        testList.push(190);
        System.out.println(testList);
//        assertEquals("190 70 50", testList.toString());
//        assertEquals(190, (int) testList.pop());
//        assertEquals("70 50", testList.toString());
    }
}
