/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fifo_animal_shelter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void animalShelter_testEnqueueDequeueCat(){
        AnimalShelter shelter = new AnimalShelter();
        Cat bob = new Cat("bob");
        shelter.enqueue(bob);
        assertEquals("Should return bob", "bob", shelter.dequeue(bob).toString());
    }

    @Test
    public void animalShelter_testEnqueueDequeueDog(){
        AnimalShelter shelter = new AnimalShelter();
        Dog fido = new Dog("fido");
        shelter.enqueue(fido);
        assertEquals("Should return fido", "bob", shelter.dequeue(fido).toString());
    }

    @Test
    public void animalShelter_testEnqueue(){
        AnimalShelter shelter = new AnimalShelter();

        assertEquals("Should return null", null, shelter.dequeue());















    }
}
