/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fifo_animal_shelter;

public class AnimalShelter extends Queue{
    protected Queue cat;
    protected Queue dog;

    public AnimalShelter(){
        this.cat = new Queue();
        this.dog = new Queue();
    }

    public void enqueue(Cat cat){
        this.cat.enqueue(cat);
    }

    public void enqueue(Dog dog){
        this.dog.enqueue(dog);
    }

    public Object dequeue(Cat cat){
        return this.cat.dequeue();
    }


    public Object dequeue(Dog dog){
        return this.dog.dequeue();
    }

    public Object dequeue(){
        return null;
    }


}
