/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package left_join;

import com.sun.jdi.Value;

import java.util.HashMap;
import java.util.Map;

public class LeftJoin {


    public HashMap combineWords(HashMap input1, HashMap input2){
        HashMap<String, String> synonym = new HashMap<>(input1);
        HashMap<String, String> antonym = new HashMap<>(input2);
        HashMap<String, String> resultMap = new HashMap<>(synonym);

        for (Map.Entry<String, String> e : antonym.entrySet())
            resultMap.merge(e.getKey(), e.getValue(), String::concat);

        return resultMap;
    }

}
