/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked_list;

import java.util.ArrayList;
import java.util.List;

public class Library {
    Node head;

    private static class Node{
        // value
        int value;

        Node next;

        // constructor
         private Node(int value, Node next){
            this.value = value;
            this.next = next;
        }
    }

    void insert(int value){
        Node newNode;

        if(head == null) {
            newNode = new Node(value, null);
            head = newNode;
        } else {
            newNode = new Node(value, head);
            head = newNode;
        }
    }

    boolean includes(int searchValue){
        Node current = head;

        while(current != null) {
            if(current.value == searchValue) {
                return true;
            }
            current = current.next;
        }
        return false;
    }

    List<Object> print() {
        List<Object> nodeList = new ArrayList<>();

        Node current = head;

        while (head != null) {
            nodeList.add(current.value);
        }

        return nodeList;
    }

}
