/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree_intersection;

public class TreeIntersection {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new TreeIntersection().getGreeting());
    }
}
