/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binary_tree_and_bst_implementation;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        BinarySearchTree classUnderTest = new BinarySearchTree();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.yes());
    }
}
