/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package breadth;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testBinaryTreeConstructorEmpty(){
        BinaryTree tree = new BinaryTree();
        assertNull(tree.getRoot());
    }

    @Test public void testBinaryTreeConstructorWithValue(){
        BinaryTree tree = new BinaryTree("john");
        assertEquals("john", tree.getRoot().getValue());
    }
}
